include $(srctree)/drivers/misc/mediatek/Makefile.custom

obj-$(CONFIG_MTK_LEDS) := leds.o
##// <<< 2016/02/04-dangyiwang, porting lm3533 from cosmos/lavender L to M
obj-$(CONFIG_MTK_LEDS) += leds_lm3533.o
##// >>> 2016/02/04-dangyiwang, porting lm3533 from cosmos/lavender L to M