
include $(srctree)/drivers/misc/mediatek/Makefile.custom

# Module project related part

ifeq ($(CONFIG_MTK_MPU6515A),y)
obj-y	+=  mpu6515/
endif

ifeq ($(CONFIG_MTK_BMA250E),y)
obj-y	+=  bma250e/
endif